/*
  SEMANA 1

*/
CREATE TABLE TBLCLIENTE (
  ID INT NOT NULL AUTO_INCREMENT,
  EMPRESA VARCHAR(20) NOT NULL,
  NOME VARCHAR(150) NOT NULL,
  EMAIL VARCHAR(250),
  DT_NASCIMENTO TIMESTAMP,
  DT_CRIADO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(ID, EMPRESA),
  KEY (EMPRESA)
);

COMMIT;

