/*
  SEMANA 1

*/
CREATE TABLE TBLCLIENTE (
  EMPRESA      VARCHAR(40) NOT NULL,
  ID           INT(10) NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(150) NOT NULL,
  EMAIL        VARCHAR(250),
  CPF          VARCHAR(20),
  CNPJ         VARCHAR(20),
  TIPO         VARCHAR(1),
  DTNASCIMENTO TIMESTAMP,
  DTCRIADO     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO  TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);
COMMIT;

CREATE TABLE TBLEMPRESA (
  ID                INT(10) NOT NULL AUTO_INCREMENT,
  CNPJ              VARCHAR(20) NOT NULL,
  RAZAOSOCIAL       VARCHAR(150) NOT NULL,
  INSCRICAOESTADUAL VARCHAR(20) NOT NULL,
  NOMEFANTASIA      VARCHAR(250),
  ENDERECO          VARCHAR(250),
  NUMERO            VARCHAR(20),
  EMAIL             VARCHAR(250),
  TELEFONE          VARCHAR(20),
  CELULAR           VARCHAR(20),
  WHATAPP           VARCHAR(20),
  COMPLEMNTO        VARCHAR(100),
  BAIRRO            VARCHAR(100),
  CIDADE            VARCHAR(100),
  ESTADO            CHAR(2),
  CEP               VARCHAR(10),
  REGIMETRIBUTARIO  VARCHAR(50),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(ID)
);

CREATE TABLE TBLESTADO (
    EMPRESA           VARCHAR(40) NOT NULL,
    ID                INT(10) AUTO_INCREMENT,
    NOME              VARCHAR(100) NOT NULL,
    SIGLA             CHAR(2) NOT NULL,
    DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EMPRESA, ID),
    KEY (ID)
);

CREATE TABLE TBLEMPRESA (
  ID                INT(10) NOT NULL AUTO_INCREMENT,
  CNPJ              VARCHAR(20) NOT NULL,
  RAZAOSOCIAL       VARCHAR(150) NOT NULL,
  INSCRICAOESTADUAL VARCHAR(20) NOT NULL,
  NOMEFANTASIA      VARCHAR(250),
  ENDERECO          VARCHAR(250),
  NUMERO            VARCHAR(20),
  EMAIL             VARCHAR(250),
  TELEFONE          VARCHAR(20),
  CELULAR           VARCHAR(20),
  WHATAPP           VARCHAR(20),
  COMPLEMNTO        VARCHAR(100),
  BAIRRO            VARCHAR(100),
  CIDADE            VARCHAR(100),
  ESTADO            CHAR(2),
  CEP               VARCHAR(10),
  REGIMETRIBUTARIO  VARCHAR(50),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(ID)
);

CREATE TABLE TBLESTADO (
    EMPRESA           VARCHAR(40) NOT NULL,
    ID                INT(10) AUTO_INCREMENT,
    SIGLA             CHAR(2) NOT NULL,
    NOME              VARCHAR(100) NOT NULL,
    CODIGOIBGE        VARCHAR(5),
    DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EMPRESA, ID),
    KEY (ID)
);

CREATE TABLE TBLCIDADE (
    EMPRESA           VARCHAR(40) NOT NULL,
    ID                INT(10) AUTO_INCREMENT,
    NOME              VARCHAR(100) NOT NULL,
    IDESTADO          INT(10),
    DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EMPRESA, ID),
    KEY (ID)
);

CREATE TABLE CEP (
    EMPRESA           VARCHAR(40) NOT NULL,
    ID                INT(10) AUTO_INCREMENT,
    CEP               VARCHAR(10) NOT NULL,
    LOGRADOURO        VARCHAR(255),
    BAIRRO            VARCHAR(100),
    IDTABELA          VARCHAR(100),
    IDCIDADE          INT(10),
    IDESTADO          INT(10),
    DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EMPRESA, ID),
    KEY (ID)
);
