/*
  SEMANA 1
*/
CREATE TABLE TBLEMPRESA (
  ID                INT(10) NOT NULL AUTO_INCREMENT,
  CNPJCPF           VARCHAR(20) NOT NULL,
  RAZAOSOCIAL       VARCHAR(150) NOT NULL,
  TIPO              ENUM('F','J') DEFAULT 'J',/*F - FISICA, J - JURIDICA*/
  INSCRICAOESTADUAL VARCHAR(20),
  NOMEFANTASIA      VARCHAR(250),
  REGIMETRIBUTARIO  VARCHAR(50),
  SITE              VARCHAR(250),
  EMAIL             VARCHAR(250),
  TELEFONE          VARCHAR(20),
  CELULAR           VARCHAR(20),
  WHATSAPP          VARCHAR(20),
  ESTADO            VARCHAR(2),
  CIDADE            VARCHAR(80),
  ENDERECO          VARCHAR(250),
  NUMERO            VARCHAR(20),
  BAIRRO            VARCHAR(100),
  COMPLEMNTO        VARCHAR(30),
  CEP               VARCHAR(10),
  SISTEMA           ENUM('00000001','00000002') DEFAULT NULL,
  ATIVO	            ENUM('A','I') DEFAULT 'A',/*A->ATIVO, I->INATIVO*/
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(ID));
COMMIT;

CREATE TABLE TBLCLIENTE (
  EMPRESA      VARCHAR(40) NOT NULL,
  ID           INT(10) NOT NULL AUTO_INCREMENT,
  NOME         VARCHAR(150) NOT NULL,
  EMAIL        VARCHAR(250),
  CPF          VARCHAR(20),
  CNPJ         VARCHAR(20),
  TIPO         VARCHAR(1),
  DTNASCIMENTO TIMESTAMP,
  ATIVO	       ENUM('A','I') DEFAULT 'A',/*A->ATIVO, I->INATIVO*/
  DTCRIADO     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO  TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);
COMMIT;

CREATE TABLE TBLREGIAO (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) AUTO_INCREMENT,
  NOME              VARCHAR(100) NOT NULL,
  SIGLA             CHAR(2) NOT NULL,
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

CREATE TABLE TBLESTADO (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) AUTO_INCREMENT,
  SIGLA             CHAR(2) NOT NULL,
  NOME              VARCHAR(100) NOT NULL,
  CODIGOIBGE        VARCHAR(10),
  REGIAO            INT(10),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

CREATE TABLE TBLCIDADE (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) AUTO_INCREMENT,
  NOME              VARCHAR(100) NOT NULL,
  IDESTADO          INT(10),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

CREATE TABLE TBLCEP (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) AUTO_INCREMENT,
  CEP               VARCHAR(10) NOT NULL,
  LOGRADOURO        VARCHAR(255),
  BAIRRO            VARCHAR(100),
  IDTABELA          VARCHAR(100),
  IDCIDADE          INT(10),
  IDESTADO          INT(10),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

CREATE TABLE TBLPAGAR (
  EMPRESA      VARCHAR(40) NOT NULL,
  ID           INT(10) NOT NULL AUTO_INCREMENT,
  DOCUMENTO    VARCHAR(20),
  TIPO	       ENUM('D','C'),/*D-DEBITO, C-CREDITO*/
  PRECO        DECIMAL(10,2),
  DTLANCAMENTO DATETIME DEFAULT NULL,
  DTVENCIMENTO DATETIME DEFAULT NULL,
  OBSERVACAO   VARCHAR(500),
  FORNECEDOR   INT(10),
  STATUS       ENUM('A','P','T') DEFAULT 'A',/*A->ABERTO,P->PARCIAL, T->TOTAL*/
  ORIGEM       VARCHAR(10),
  TIPODOC      INT(10),
  DTCRIADO     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO  TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);
COMMIT;

CREATE TABLE TBLRECEBER (
  EMPRESA      VARCHAR(40) NOT NULL,
  ID           INT(10) NOT NULL AUTO_INCREMENT,
  DOCUMENTO    VARCHAR(20),
  TIPO	       ENUM('D','C'),/*D-DEBITO, C-CREDITO*/
  PRECO        DECIMAL(10,2),
  DTLANCAMENTO DATETIME DEFAULT NULL,
  DTVENCIMENTO DATETIME DEFAULT NULL,
  OBSERVACAO   VARCHAR(500),
  CLIENTE      INT(10),
  STATUS       ENUM('A','P','T') DEFAULT 'A',/*A->ABERTO,P->PARCIAL,T->TOTAL*/
  ORIGEM       VARCHAR(10),
  TIPODOC      INT(10),
  DTCRIADO     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO  TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);
COMMIT;

CREATE TABLE TBLPROGRAMA (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) NOT NULL AUTO_INCREMENT,
  NOME              VARCHAR(40) NOT NULL,
  DESCRICAO         VARCHAR(250),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

CREATE TABLE TBLPROJETO (
  EMPRESA           VARCHAR(40) NOT NULL,
  ID                INT(10) NOT NULL AUTO_INCREMENT,
  NOME              VARCHAR(40) NOT NULL,
  IDPROGRAMA        INT(10),
  DATAINICIAL       TIMESTAMP,
  DATAFINAL         TIMESTAMP,
  DESCRICAO         VARCHAR(500),
  PUBLICO           VARCHAR(250),
  RESPONSAVEL       VARCHAR(100),
  EMAIL             VARCHAR(250),
  URLFOTO           VARCHAR(250),
  TELEFONE          VARCHAR(20),
  OPERADORA         VARCHAR(20),
  DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(EMPRESA, ID),
  KEY (ID)
);

-- CREATE TABLE TBLFONESPROJETOS (
--   EMPRESA           VARCHAR(40) NOT NULL,
--   ID                INT(10) NOT NULL AUTO_INCREMENT,
--   PROJETO         VARCHAR(40) NOT NULL,
--   NUMERO            VARCHAR(40) NOT NULL,
--   OPERADORA         VARCHAR(40) NOT NULL,
--   DTCRIADO          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   DTALTERACAO       TIMESTAMP on UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY(ID)
-- );
